CREATE TABLE IF NOT EXISTS team (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS pokemon (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  base_experience INT NOT NULL,
  sprite VARCHAR(255) NOT NULL,
  abilities VARCHAR(255) NOT NULL,
  types VARCHAR(255) NOT NULL,
  team_id INT REFERENCES team(id) ON DELETE SET NULL
);


