CREATE TABLE IF NOT EXISTS team (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS team_pokemon (
  team_id INT REFERENCES team(id) ON DELETE SET NULL,
  id SERIAL NOT NULL,
  name VARCHAR(255) NOT NULL,
  base_experience INT NOT NULL,
  sprite VARCHAR(255) NOT NULL,
  abilities VARCHAR(255) NOT NULL,
  types VARCHAR(255) NOT NULL,
  external_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (team_id, id)
);